name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  verify_release_tag:
    name: Verify tag version
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Verify tag
        run: |
          tag=${{ github.ref_name }}
          tag=${tag:1}
          grep -F -q "$tag" pyproject.toml
  build_wheels:
    needs: [ verify_release_tag ]
    uses: ./.github/workflows/build.yml
  release:
    name: Create release
    permissions:
      contents: write
    needs: [ build_wheels ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1